"""
Resonant Cognition v17 — Global Constants
==========================================
"Let there be light."

All tunable parameters live here. Changing a value in this file should never
require touching logic code. Tuned empirically after the orbital acceptance test.

NOTE: This file is (partially) generated by calibrate_axes.py. The AXIS_* vectors
below are Option B placeholders derived from MiniLM anchor-phrase averages — see
docs/phase0d_drafts.md §B. Re-running calibration rewrites ONLY that section.
"""

import os

# ─── GRAVITATION ───────────────────────────────────────────────────────────────

G = 5.0                    # Gravitational constant. C_core (M=10) dominates at r>=2.
EPSILON = 0.1              # Softening length — dampens close-approach spikes
DT = 0.01                  # Integration timestep for velocity Verlet

# ─── CORE MASS MODEL: M_core = M_base + alpha*(dD)^beta ──────────────────────

M_CORE_BASE = 10.0         # Dominates all planets (planets are 2.0–4.5)
DISSONANCE_ALPHA = 1.2     # How strongly dissonance increases effective mass
DISSONANCE_BETA = 1.8      # Exponent — higher = sharper ramp under stress

# ─── PLANET MASSES (cognitive weight / activation threshold, not grav mass) ──

PLANET_MASSES = {
    "sage":       3.0,
    "magician":   3.5,
    "caregiver":  4.5,
    "hero":       2.0,
    "everyman":   2.8,
    "rebel":      3.2,
    "ruler":      4.0,
}
# Planet-planet & giant gravity DISABLED: cognitive interaction between archetypes
# is SEMANTIC resonance (Phase 0D), not Newtonian gravity (Maya spec + empirical).
PLANET_GRAVITY_SCALE = 0.0
GIANT_GRAVITY_SCALE = 0.0

# ─── SEMANTIC VOLUME (sigma — Gaussian spread for field evaluation) ──────────

PLANET_SIGMA = {
    "sage":       1.2,
    "magician":   1.8,
    "caregiver":  0.8,
    "hero":       2.0,
    "everyman":   1.4,
    "rebel":      1.1,
    "ruler":      1.0,
}

MOON_DAMPING_BASE = 0.0    # True friction on moons; 0 = pure conservative N-body

# ─── ORBITAL INITIALIZATION ──────────────────────────────────────────────────

PLANE_TILT_MAX_DEG = 5     # Max random tilt from reference orbital plane
ORBITAL_VEL_FORMULA = "circular"

# ─── RESONANCE (Phase 0D) ────────────────────────────────────────────────────

RESONANCE_THRESHOLD = 0.7  # Cosine similarity threshold for constructive resonance
RESONANCE_SIGMOID_K = 8.0  # Sharpness of sigmoid ramp above threshold
# Resonance_n = 1 / (1 + exp(-k * (similarity - threshold)))
#
# RESONANCE_MULTIPLIER_ENABLED : Phase 1 "resonance multiplier" knob — ON by default.
#   When True, routing.py multiplies each planet's field-derived activation weight by
#   sigmoid(k*(sim - threshold)) using its semantic-identity cosine. When False,
#   the output is byte-identical to the no-multiplier path so it can be A/B'd later with
#   zero rewrite. Kept because collapse()'s consensus+tension already IS the interference
#   mechanic in practice; stacking a second sigmoid on top risks double-counting (see D-018 §7b/7c).
#   NOTE: was originally OFF; switched to True after A/B testing confirmed it improves
#   routing spread without causing ruler-collapse at FIELD_POSITION_WEIGHT=0.30.
RESONANCE_MULTIPLIER_ENABLED = True
# RESONANCE_MULTIPLIER_THRESHOLD : cosine threshold for the Q4 post-collapse multiplier.
#   This operates in FULL 384-dim space (input_vec vs planet wave center), NOT the 3-axis
#   projection used by Phase-0D's RESONANCE_THRESHOLD=0.7. In 384-dim, MiniLM scatters
#   most prompt-vs-identity cosines around ±0.1, so a threshold of 0.7 would give sigmoid≈0
#   for every planet (measured: all multipliers <0.01 — catastrophic crush). Threshold=0.0
#   gives reasonable spread (0.38–0.71 range) as a gentle "you align with this question" nudge.
#   TUNABLE: lower it to make the multiplier more permissive; raise it to be stricter.
RESONANCE_MULTIPLIER_THRESHOLD = 0.0

# ─── PHASE 1 ROUTING / SPIKE DETECTION ─────────────────────────────────────
# FIELD_POSITION_WEIGHT : blend weight for the planet's field center, per Q1 approval.
#   field_center = w * wave_center_384d + (1 - w) * projected_orbital_position
#     w = 1.0 -> pure semantic identity (position ignored; static game map)
#     w = 0.0 -> pure orbital position (identity ignored; rigid spatial map)
#   Tuning this knob is a dial, NOT a rewrite: if the 3D projection starts causing
#   RULER-COLLAPSE (language compresses into a narrow cone), turn it DOWN toward identity.
#   "Identity travels with position" — the planet carries its psychological weight
#   along its orbital path. Start at 0.5 (balanced); nudge in Segment 2/4 tuning.
FIELD_POSITION_WEIGHT = 0.5
# FIELD_DISTANCE_METRIC : how routing measures "closeness" between the input and a
#   planet's field center (Segment 2). A TOGGLE, not an architecture choice — flip it to
#   A/B without rewriting anything:
#     "angular_z" -> per-input z-score of angular distances across all planets.
#                    MEASURED WINNER (tuning spike): MiniLM scatters real prompts ~90deg
#                    from ALL archetype texts, so raw angles cluster in a narrow band and
#                    no sigma can discriminate. Z-scoring makes the field self-calibrating
#                    per prompt: for every input the cohort mean is 0 and sd is 1 BY
#                    CONSTRUCTION, so "closest planet" always means something. Default.
#     "angular"   -> angular separation between unit directions (scale-invariant; reuses
#                    the exact comparison collapse.py already uses in Phase 0D). Kept for
#                    A/B — good when inputs are close to archetypes, weak on scattered prompts.
#     "euclidean" -> straight-line distance in 384-dim. Literal build-plan formula, but
#                    fragile: raw lifted positions sit at radius ~7-12 while inputs/
#                    identities are unit vectors (~1), so distances get dominated by that
#                    radius gap and the field can flatten (RULER-COLLAPSE family).
FIELD_DISTANCE_METRIC = "angular_z"
# SIGMA_SCALE : converts a planet's PLANET_SIGMA value into the spread used in the
#   Gaussian exp(-d^2 / 2 sigma_eff^2). In angular mode d is in radians, so this scales
#   sigma to radians. GUESS-tuned; nudge in Segment 4 like every other knob.
SIGMA_SCALE = 1.0

# Wave-speech mode for the collapse engine (collapse.py):
#   "vector" — dumb planets: each wave is its semantic anchor pulled by relevance. No LLM calls.
#   "llm"    — 7 distinct voices actually generate a 'piece' via the Ring/chamber model, then embed.
#              (Stub exists in collapse.emit_waves_llm; full build is a later phase.)
WAVE_SPEECH_MODE = "vector"

# ─── MULTI-PASS RECURSIVE FEEDBACK (Phase 0H — the Echo) ─────────────────────
# "Waves reacting to waves." A thought isn't a single splash: each planet feels how
# the rest of the system reacted (the tension/cancellation field) and adjusts its posture
# before the waveform is finally observed. Pass 1 = initial superposition; later passes feed
# that result back in so planets repel from their opponents and lean toward consensus.
#
# ECHO_ENABLED : master toggle. False -> single-pass, byte-identical to pre-0H behavior
#                (kept for debugging / A-B comparison). True -> ECHO_PASSES total passes.
# ECHO_PASSES  : total superposition passes including the initial splash. 2 = one echo.
ECHO_ENABLED = True
ECHO_PASSES = 2
# Gains below are GUESSES (tuned by feel, not real session data yet). Debug handles:
#   ECHO_TENSION_GAIN  — how much a planet pulls back when the field is tense overall.
#   ECHO_ALIGN_REPEL   — how hard each planet moves AWAY from the voices it cancelled
#                        against (the debate response; larger = more contrarian pushback).
#   ECHO_CONSENSUS_PULL— how strongly every wave leans toward the group consensus vector
#                        (echo-chamber convergence; keep LOW to preserve individuality).
ECHO_TENSION_GAIN = 0.5
ECHO_ALIGN_REPEL = 0.35
ECHO_CONSENSUS_PULL = 0.12

# ─── PHASE 3 CHAMBER: MOON HEMISPHERE FRAMING (toggle, OFF by default) ────────
# The Build Plan's Phase A spec says each planet fires TWO shaped sub-perspectives
# before merging into one raw Id response:
#   LEFT moon  -> frames the response rationally / analytically.
#   RIGHT moon -> frames it intuitively / affectively (the felt sense).
# When MOON_HEMISPHERE_ENABLED is True, Phase A runs that two-lens split per planet
# and merges the lenses into a single Id response. When False (default), Phase A uses
# the original single raw-Id prompt — byte-for-byte identical to pre-toggle behavior,
# so existing test_phase_a/b/c.py results are unaffected until we deliberately flip it.
#
# This is a DIAL, not an architecture rewrite: turning it ON adds one extra LLM call
# per planet in Phase A (2 lenses + 1 merge) and is designed to be A/B'd later without
# touching any other phase. Kept OFF by default because the chamber just stabilized on
# the single-Id path; we flip it on when its own dedicated test segment runs.
MOON_HEMISPHERE_ENABLED = False
# How many words of raw Id each lens should produce before merging (guides the prompt).
MOON_LENS_MAX_TOKENS = 192
# Merged final Id response length budget (kept in line with the original Phase A's ~512).
MOON_MERGE_MAX_TOKENS = 512

# ─── PHASE 3 CHAMBER: COMET B→C BASIC TRIGGER CHECK (toggle, OFF by default) ──
# Per Build Plan Phase 3: between Ego (B) and Superego (C), a BASIC trigger fires —
#   "if the dominant planet has led for N consecutive sessions, a Comet appears with
#    a contrarian reframe prompt" and its line is folded into the Phase C discussion.
#
# This is the MINIMAL basic version only. The full 4-condition refinement (stagnation /
# over-seriousness / binary convergence / random 2% injection from comet/jester.json)
# is explicitly DEFERRED to Phase 8 — do NOT build that here. Keep it small.
#
# How "dominant" is decided: the planet with the highest routed weight for this input
# (max(routed_weights)). Cross-session history lives in a TINY state file next to the
# code (COMET_STATE_FILE) — deliberately minimal, NOT the Phase 4/8 memory machinery.
#
# Toggle OFF by default = existing test_phase_a/b/c.py results are byte-identical until
# we flip it on for its own dedicated test segment (same reasoning as the moon toggle).
COMET_TRIGGER_ENABLED = False
# Number of CONSECUTIVE sessions the same planet must have been #1 before the Comet
# appears. 3 matches John's "once is fluke, twice coincidence, three times pattern" rule.
# TUNABLE: raise to make it rarer, lower (2) to make it appear sooner.
# The comet FIRES the moment the dominant planet has now led for this many CONSECUTIVE
# sessions (i.e. on the N-th straight one). With 3: session1->no, session2->no, session3->yes.
COMET_CONSECUTIVE_SESSIONS = 3
# Once it has fired once, do NOT re-fire every single session during a long run. Instead
# stay quiet until the streak grows by another COMET_REFIRE_STEP consecutive sessions,
# then fire again. Deterministic (NOT random) so test logs stay repeatable; random
# re-firing is a Phase 8 refinement (comet/jester.json 'random_injection').
#   Fires at: 3, then 5, 7, 9...  (every COMET_REFIRE_STEP more straight sessions).
# A subject change (a DIFFERENT dominant planet) resets the streak to 1 automatically,
# so a genuinely new topic must rebuild to N before it can ever fire — no extra code.
COMET_REFIRE_STEP = 2
# Where the tiny cross-session dominant-planet history lives. Relative paths resolve
# next to this module's directory so it works from any CWD. A single JSON file holding
# {"streak_planet": <id or null>, "streak_count": int}.
COMET_STATE_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "comet_state.json")
# Max tokens for the Comet's contrarian reframe (kept small; it is one injected voice).
COMET_MAX_TOKENS = 256

# ─── EMBEDDING PROJECTION ONTO COGNITIVE AXES (Option B) ─────────────────────
# A 384-dim MiniLM vector is projected to [x, y, z] by dotting it with each of the
# three fixed axis direction vectors below. These are Option B placeholders: the
# unit-normalized MEAN of a few clearly-polar anchor phrases (see AXIS_ANCHOR_PHRASES
# in calibrate_axes.py), generated once against LM Studio MiniLM. They can be swapped
# for PCA-derived axes (Option A) later WITHOUT changing any calling code — the
# interface is project_to_axes(vec384) -> [x, y, z] either way.
# Axes: X=Rationality(+) vs Intuition(-), Y=Preservation(+) vs Disruption(-),
#       Z=Outward execution(+) vs Inward reflection(-).  (See phase0d_drafts.md §A.)

AXIS_RATIONALITY = [-0.079605, 0.122298, 0.046349, 0.044235, 0.070393, -0.001411, 0.093958, 0.014573, 0.008491, 0.058755, 0.049037, -0.069565, 0.078809, 0.057300, -0.057555, -0.006804, -0.053755, 0.041627, -0.054186, -0.058729, -0.125862, -0.042805, -0.027046, 0.064353, -0.001869, 0.055802, 0.015182, 0.059000, 0.063302, -0.070542, 0.054179, 0.000568, -0.001805, -0.014952, 0.074033, 0.058480, 0.076848, -0.013168, 0.068664, 0.031988, -0.033397, -0.149248, -0.064605, 0.062130, -0.050986, 0.101643, -0.011380, 0.074227, -0.053024, -0.025365, -0.075840, 0.035885, -0.057706, -0.088186, 0.015080, -0.009142, 0.015663, -0.007417, 0.009265, -0.055794, 0.041125, 0.018842, -0.086914, 0.049141, 0.106907, 0.022549, 0.015879, -0.031549, 0.029470, 0.125122, -0.050247, 0.001706, -0.025840, 0.036715, -0.041291, -0.057118, 0.003182, 0.004340, 0.026351, -0.072229, -0.013111, -0.024612, -0.006625, -0.033783, -0.014543, -0.025691, -0.008207, -0.052098, -0.003246, -0.005655, 0.082297, -0.030410, 0.010431, -0.002588, 0.079414, -0.032025, -0.105185, -0.053087, 0.044008, 0.169853, -0.049984, 0.042884, -0.030136, -0.088293, -0.038252, -0.030285, 0.047391, 0.028650, 0.127681, 0.040770, 0.029696, -0.000800, -0.012317, 0.115713, -0.005197, -0.029069, 0.009336, 0.007359, -0.047184, -0.131465, 0.043115, -0.017416, 0.026440, 0.048217, 0.021121, -0.080507, 0.008493, -0.000000, 0.006440, 0.051354, 0.029786, 0.057631, -0.039395, 0.042805, -0.050857, -0.052571, -0.040174, 0.100602, 0.005416, 0.050656, -0.037506, -0.028854, 0.015511, 0.058480, -0.019175, 0.042997, -0.002503, 0.002120, 0.070476, -0.126821, -0.015965, -0.000109, -0.050399, -0.020478, 0.038533, 0.060202, 0.036772, -0.010521, -0.012210, -0.068534, -0.020087, 0.034988, 0.014146, -0.008605, 0.016398, -0.096519, 0.029869, 0.019459, 0.001060, -0.026522, 0.038878, -0.026318, 0.001095, 0.071330, -0.058462, -0.020536, -0.027001, -0.012983, 0.011757, 0.011761, -0.007982, -0.007992, 0.013282, -0.006883, -0.096092, 0.062766, -0.003555, 0.099848, 0.039351, 0.049388, -0.032356, 0.045534, -0.159071, 0.019076, -0.106433, 0.003761, 0.111076, -0.024404, -0.077479, -0.003758, 0.045682, 0.015909, 0.050696, -0.065731, -0.059668, -0.025487, 0.016316, -0.029762, -0.020118, 0.021804, 0.012585, 0.014683, 0.040235, -0.048245, -0.063893, -0.054484, -0.049348, 0.049318, -0.086690, -0.011942, 0.096050, -0.047865, 0.038904, 0.000000, -0.114764, 0.038278, 0.028005, 0.004808, -0.055213, -0.022213, -0.008759, -0.051782, -0.009785, -0.033829, -0.012695, -0.007783, 0.061678, -0.044597, -0.053842, 0.002448, 0.027191, -0.039813, -0.003144, 0.007199, 0.036396, 0.051264, -0.025907, 0.024374, -0.031945, 0.046090, 0.016876, 0.072971, -0.005179, 0.011810, -0.029779, 0.017362, 0.009280, -0.029784, -0.059641, -0.081881, 0.095367, 0.106353, -0.029939, 0.032838, 0.084919, 0.011961, 0.032122, -0.045948, 0.022544, -0.024773, 0.038902, 0.081150, -0.019331, -0.045460, -0.013822, -0.071591, 0.024279, -0.051018, -0.037664, 0.004499, 0.033933, -0.013404, -0.036953, 0.042024, -0.071203, 0.037870, -0.027864, 0.132244, 0.029016, -0.099433, -0.051227, 0.001403, 0.071460, 0.003195, 0.025243, 0.009627, -0.122502, -0.001395, 0.055614, -0.027720, -0.070505, 0.028185, 0.030762, 0.005062, 0.006982, -0.028974, 0.051544, -0.005283, -0.051687, 0.003132, 0.075304, -0.058434, -0.050910, 0.040589, -0.042545, 0.004839, 0.016598, -0.052683, -0.008927, -0.000000, -0.026179, -0.032723, 0.076741, -0.000108, 0.040630, -0.013862, -0.012162, -0.025714, 0.004236, -0.037007, 0.066118, 0.026370, -0.027082, 0.043511, 0.012658, 0.068044, -0.080372, -0.009777, -0.083416, 0.022472, 0.011257, 0.010674, 0.043364, -0.008650, 0.062618, 0.030218, -0.035568, 0.064991, 0.021585, 0.019466, -0.005598, 0.020516, 0.059705, -0.036060, 0.065023, -0.076674, 0.015484, 0.049218, 0.005131, -0.021907, -0.078654, -0.006976, -0.013115, -0.028670, -0.016462, -0.027225, -0.006876, -0.028510, -0.084799, 0.013918, 0.006863, 0.005002, 0.023016, 0.037511, 0.000363, -0.039629, -0.005605, 0.022702, -0.036424, 0.031637, 0.079495, 0.134362, 0.102859, -0.040447]
AXIS_PRESERVATION = [-0.063856, 0.088370, 0.001311, -0.025307, 0.046218, 0.012881, 0.002138, -0.094059, 0.005259, 0.057071, 0.018853, 0.094311, -0.012623, -0.024985, -0.036779, 0.023694, 0.017716, 0.043803, -0.147120, 0.009152, -0.063230, -0.005695, -0.026980, 0.065404, -0.093080, 0.072917, -0.010693, -0.017648, 0.065733, -0.121962, -0.008334, -0.004377, 0.022002, 0.015965, -0.050694, 0.113119, 0.057121, -0.091620, 0.038983, -0.066244, -0.075808, -0.032329, -0.033737, -0.039402, -0.018404, 0.042860, 0.049977, -0.027952, -0.010395, -0.047228, -0.011763, -0.019990, -0.036464, 0.047163, 0.076958, 0.024938, 0.063428, -0.010493, -0.055451, -0.014371, 0.061837, 0.046275, -0.041895, 0.026591, 0.033512, 0.004945, -0.004454, 0.065468, -0.017229, 0.080689, -0.032547, 0.011859, -0.015968, 0.049569, -0.039423, 0.000236, -0.017599, -0.115129, 0.034904, 0.013083, 0.026171, -0.044342, 0.020886, 0.049510, 0.007660, -0.001951, 0.028188, -0.039050, 0.065148, -0.004402, -0.026802, 0.013943, 0.177837, -0.046701, -0.008451, -0.005091, 0.025570, 0.027918, -0.034286, 0.148879, 0.025056, 0.056085, -0.015807, -0.052590, -0.001503, -0.078136, -0.037991, -0.011017, 0.036416, 0.076868, -0.050265, 0.039864, -0.092941, 0.053928, -0.026467, 0.008218, -0.010673, 0.032418, -0.034556, -0.042148, 0.070583, 0.033378, 0.086568, 0.008772, 0.006710, -0.017799, 0.052403, -0.000000, -0.023449, -0.053188, 0.006910, 0.044780, -0.040409, 0.003989, -0.032619, -0.041454, 0.001008, -0.033857, 0.067694, 0.067830, -0.053303, -0.023555, 0.022384, -0.037948, -0.036750, 0.052020, 0.080511, -0.029755, 0.023322, 0.013231, -0.038369, -0.003439, 0.052320, 0.021528, 0.031210, 0.023769, -0.068567, 0.020385, 0.007060, 0.024043, -0.037250, -0.040317, -0.038220, 0.045485, -0.040439, -0.055173, 0.045252, -0.135296, -0.019406, 0.051588, -0.020823, 0.053484, 0.148367, 0.017026, 0.006347, 0.042389, -0.062807, 0.004731, 0.000886, 0.046670, 0.011079, -0.091653, -0.109076, -0.078439, -0.010269, 0.009750, -0.022958, -0.070320, 0.072161, -0.005654, -0.049700, 0.064902, 0.040271, 0.068888, -0.050859, -0.057672, 0.019971, -0.049316, -0.056988, 0.005543, -0.054307, -0.002716, -0.069640, -0.030294, -0.034000, -0.020610, -0.028675, -0.071580, 0.001923, -0.011481, -0.060015, 0.075514, 0.108031, -0.035730, 0.086357, 0.000657, 0.011813, 0.078044, -0.025377, -0.017154, 0.087005, 0.005021, 0.030903, 0.000000, 0.002291, -0.030358, -0.086152, 0.111226, -0.037206, -0.005409, -0.115077, -0.101850, -0.060794, -0.020106, -0.047298, -0.027012, 0.019658, 0.022754, -0.048630, -0.053450, 0.028946, -0.016206, -0.053362, 0.006915, 0.010453, 0.015580, -0.053841, 0.139523, -0.033174, 0.052879, -0.087637, -0.068510, 0.026226, -0.065893, -0.029827, -0.078107, -0.050619, -0.013396, 0.008889, -0.056657, 0.016118, -0.017393, -0.036303, 0.044300, 0.008924, 0.030961, -0.083627, 0.022253, 0.009659, 0.003382, 0.030308, 0.020043, -0.045363, -0.021732, 0.050794, -0.034191, -0.027875, -0.093054, 0.052680, 0.064041, -0.001824, -0.016209, -0.050342, 0.031971, 0.015948, 0.075151, -0.011870, 0.088490, 0.006653, 0.013849, 0.012734, 0.093207, -0.026555, -0.017295, 0.039936, -0.061544, -0.046388, -0.056006, 0.017285, -0.041645, -0.001254, -0.059176, -0.017278, 0.074470, -0.049154, -0.025297, -0.024427, -0.000570, 0.035282, 0.023129, -0.023605, -0.070811, 0.074360, 0.038543, -0.057646, 0.008324, -0.116144, -0.054589, -0.037960, -0.000000, 0.011902, 0.016926, -0.008718, 0.047976, 0.018455, -0.028733, 0.046589, -0.089603, 0.006859, 0.036596, -0.000183, 0.026678, 0.021461, 0.018057, 0.013664, 0.021688, 0.045897, -0.040951, -0.106154, 0.011553, -0.000535, 0.013902, 0.054301, -0.002638, 0.023728, -0.003827, 0.108147, 0.018626, 0.049119, 0.182889, 0.059729, 0.033848, 0.022419, 0.038172, -0.014973, -0.006175, 0.010760, 0.057954, 0.097681, 0.016547, -0.035454, 0.045651, -0.013584, 0.091838, -0.023802, -0.008494, 0.005516, -0.001322, -0.032698, -0.022512, -0.002446, -0.018414, 0.045885, 0.100722, 0.039334, -0.027462, 0.080736, 0.079356, 0.021365, -0.038529, 0.059257, -0.040625, 0.097378, 0.049921]
AXIS_OUTWARD = [0.029446, 0.032603, 0.024259, -0.005646, 0.002093, -0.020630, 0.041113, 0.010620, -0.026550, 0.013820, 0.090642, -0.053356, -0.075031, 0.022791, 0.056050, 0.006125, 0.074773, 0.022704, -0.071470, 0.016212, -0.028454, -0.007773, -0.046974, 0.027503, -0.109875, 0.013426, 0.005934, -0.037419, 0.089653, -0.026474, 0.090076, 0.021615, 0.035486, 0.027367, -0.041785, 0.144488, -0.007971, -0.043997, -0.005990, -0.068380, 0.023713, -0.101615, -0.056641, -0.004470, 0.027655, -0.034804, 0.017580, -0.011450, -0.016937, -0.083994, -0.019165, 0.001184, -0.031340, -0.098115, -0.017536, 0.062166, 0.083913, 0.043800, 0.030791, -0.037171, -0.029300, -0.007879, 0.020437, 0.042202, 0.076957, 0.052532, 0.077815, -0.025861, 0.022043, 0.053056, 0.024352, 0.008731, -0.005728, -0.013068, -0.061848, -0.016007, -0.020240, -0.015838, -0.008946, -0.043377, 0.059826, -0.053680, -0.025749, 0.047588, 0.044908, 0.014932, -0.040252, 0.024203, 0.119386, 0.048734, -0.010423, -0.033389, -0.031018, 0.020283, 0.004111, -0.034519, -0.016405, -0.075602, -0.094828, 0.188111, -0.014837, 0.061384, -0.076038, -0.064030, 0.035414, -0.036085, -0.016869, -0.027925, -0.076631, -0.027328, -0.016609, -0.038291, -0.007369, 0.000066, 0.029842, 0.023288, 0.050415, 0.016551, 0.037117, -0.054693, 0.110743, 0.013173, -0.006987, 0.078369, 0.016390, -0.076181, 0.015010, -0.000000, 0.015625, -0.070140, 0.024481, 0.007452, -0.040417, -0.031895, 0.063460, -0.028331, -0.045385, -0.003121, 0.059495, -0.052024, 0.055267, 0.054353, 0.042486, 0.035218, -0.002407, 0.041201, 0.014932, 0.042256, 0.027673, -0.034584, -0.032771, -0.015672, 0.008989, -0.006048, -0.012946, -0.019705, -0.057914, 0.031342, 0.060247, 0.006391, -0.098522, 0.093461, 0.014550, -0.024483, -0.062253, -0.012073, 0.019476, -0.115032, -0.007214, 0.021402, -0.029618, -0.052258, 0.092967, -0.003482, -0.053989, 0.060503, 0.043625, 0.017979, 0.088530, 0.077337, 0.032627, -0.073331, 0.038075, -0.006440, -0.010913, 0.071064, 0.009293, 0.083914, -0.010951, 0.022179, -0.112571, 0.134838, -0.105228, -0.047682, -0.100707, -0.065546, 0.013374, 0.003077, -0.062734, 0.069293, 0.006663, 0.006303, -0.008577, -0.041454, 0.007735, -0.137311, -0.005911, 0.013490, 0.027755, 0.049170, -0.044028, 0.018862, 0.121407, 0.043621, 0.012365, -0.051737, -0.010740, 0.002694, -0.100212, -0.001723, -0.002725, -0.008130, 0.001753, 0.000000, 0.112708, -0.003929, -0.034940, 0.023482, 0.001213, -0.025151, -0.090179, -0.063010, -0.036744, 0.073368, -0.079193, 0.036840, 0.045126, 0.063727, 0.052856, -0.061673, 0.056920, -0.020856, -0.043993, 0.045208, 0.002500, 0.031962, 0.032666, 0.055737, -0.085025, 0.016325, 0.061182, 0.050081, -0.041918, 0.018002, -0.117767, -0.000649, -0.037582, 0.033929, 0.001166, 0.044221, 0.018438, 0.010195, -0.016818, -0.004030, -0.012687, -0.046273, -0.081768, 0.020750, -0.051068, -0.021857, 0.009118, 0.013930, -0.089831, 0.027009, -0.050302, 0.032418, 0.038122, -0.018051, 0.046514, -0.019773, 0.004911, -0.064941, -0.018705, 0.070522, 0.001427, 0.011423, 0.032984, -0.021791, 0.021239, -0.033909, -0.064202, 0.013949, 0.027493, 0.023474, 0.033496, -0.004077, -0.164319, -0.039458, 0.049183, -0.014154, 0.021115, -0.039513, -0.042658, 0.047160, 0.013839, 0.004366, 0.080716, 0.004826, -0.013246, -0.011142, -0.012807, -0.022089, -0.025993, 0.009465, -0.011294, 0.022691, 0.036064, 0.000579, -0.051600, -0.000000, -0.055940, -0.052742, 0.095397, 0.065601, 0.012727, 0.052267, -0.044345, -0.084496, -0.051454, -0.105372, 0.023784, 0.007036, 0.116401, 0.057623, 0.062450, -0.059720, -0.007282, -0.074614, -0.146272, 0.085468, -0.027587, 0.005573, -0.003484, -0.040334, -0.019366, -0.028688, -0.007224, 0.033651, -0.020094, 0.111508, 0.024014, 0.039398, -0.050335, 0.065008, -0.035494, -0.028901, 0.077047, 0.007748, 0.005173, -0.042383, -0.074790, 0.063693, 0.019616, 0.042585, -0.004010, 0.016970, -0.067520, -0.054906, 0.016374, 0.003255, -0.012470, -0.027891, -0.043702, 0.080933, 0.100111, 0.056265, 0.037851, -0.048381, -0.043152, 0.117699, 0.013063, -0.038851, 0.029078, -0.048278]

# ─── MEMORY / DECAY ──────────────────────────────────────────────────────────

MEMORY_MASS_BASE = 1.0         # M_u scale: mass = base * cosine(semantic, consensus) -> [0, base]
                               # (Paper III single-step form; full time-integral wired in sleep Pass V.)
DOMINANCE_ZONE_RATIO = 2.0     # Top planet weight > ratio*runner-up => dedicated planet_vault
MEMORY_POSITION_JITTER = 0.05  # Radial jitter so multiple entries per planet don't stack on one point
DECAY_GAMMA_BASE = 0.02        # Base decay rate per unit time (usage-frequency modulated)
MIN_ENTRY_MASS = 0.05          # Below this -> Black Hole compression queue
G1_DECAY_HALF_LIFE_WEEKS = None  # G1: effectively never decays (accumulation body)
G2_DECAY_HALF_LIFE_WEEKS = 4.0   # G2 self-model entries: ~4 week half-life

# ─── SLEEP CYCLE ──────────────────────────────────────────────────────────────

MICRO_SLEEP_IDLE_MINUTES = 30
DEEP_SLEEP_IDLE_HOURS = 3
STAGGER_INTERVAL_SECONDS = 5   # Per-planet Pass IV drift interval during deep sleep
WATCHKEEPER_COUNT = 3          # Planets that stay awake during deep sleep (min 1; prevents binary deadlock)

# ─── PHASE 6 RING: IDLE BEHAVIOR (Segment 4, toggle OFF by default) ─────────
# RING_IDLE_BEHAVIOR_ENABLED : master switch for generate_idle_reflection().
#   When False (default), the function returns a no-op string WITHOUT touching LM
#   Studio — so ring.py stays fully offline and the live flow is byte-identical to
#   pre-Segment-4 until John flips this on. When True, it makes ~1 LLM call reusing
#   cognitive_chamber._llm_chat_cached() and sources its "what you said earlier"
#   context from the Ring's recent swarm memory (capped by RING_IDLE_CONTEXT_ENTRIES).
# Kept OFF by default for the same reason as MOON_HEMISPHERE / COMET_TRIGGER:
# don't burn an LLM call in a path we haven't A/B'd on its own segment yet.
RING_IDLE_BEHAVIOR_ENABLED = False
# How many recent swarm entries to feed into the idle-reflection prompt. Kept small
# (2) deliberately: because Segment 2's write-everything + compression makes the swarm
# grow fast, a big context here would balloon the single LLM call against the 4090.
RING_IDLE_CONTEXT_ENTRIES = 2
# Max tokens for the ambient reflection — it is ONE short aside, not a full answer,
# so we keep it well under the ~512 budget used elsewhere (GUESS: 160).
RING_IDLE_MAX_TOKENS = 160
# Sampling temperature. Slightly higher than analytical passes because this is an
# ambient, human "thinking out loud" voice rather than a reasoned verdict.
RING_IDLE_TEMPERATURE = 0.8

# ─── PHASE 6 RING: MONTHLY SELF-REVIEW (Segment 5, toggle OFF by default) ─────
# D-009: at the 30-session mark OR calendar-month boundary -> G2 generates its
# change report -> routes through a FULL 7-planet debate (run_phase_a_b_c;
# all 7 must emit — anti-silence checked) -> verdict logged to G2's ring_buffer.
# RING_SELF_REVIEW_ENABLED : master switch. When False (default), the trigger and
#   runner are pure no-ops with ZERO LLM calls and never import cognitive_chamber
#   (same offline-safe pattern as MOON / COMET / IDLE toggles). Flip to True only
#   when you want a live review run (a ~21+ call burst — see 5b notes in Build Plan).
RING_SELF_REVIEW_ENABLED = False
# Session-count trigger: fire the self-review at this many completed sessions.
RING_SELF_REVIEW_SESSION_THRESHOLD = 30
# Report context caps (GUESS, flagged): how much history G2 may quote when it writes
# its change report. Kept small so the ~21+ call debate doesn't balloon against the
# 4090's ceiling — the debate itself is the expensive part, not the report.
RING_SELF_REVIEW_REPORT_TOPICS = 5     # recent topic labels fed to G2 for the report
RING_SELF_REVIEW_MAX_TOKENS = 384      # cap on the generated change report length

# ─── PHASE 7 GIANTS: G1 FILTER MOONS (Segment 2, toggle OFF by default in DEV) ──
# G1_FILTER_MOONS_ENABLED : master switch for g1_filter_moons.g1_filter_moons_pass().
#   When False (default — dev mode), Sleep Pass I skips the moons entirely and
#   behaves byte-identically to Segment 1 (zero LLM calls per candidate).
#
#   ⚠️ PRODUCTION RELEASE: Set this to True. The moons are a MANDATORY integrity
#   gate for G1's permanent archive — turning them off risks unverified data
#   entering the store. See Build Plan Phase 7 Seg 2 note.
#   In production, do NOT expose this as a user-facing runtime toggle; it should
#   be locked to True in the release config.
G1_FILTER_MOONS_ENABLED = False
# Relevance floor: candidates scoring below this are marked "peripheral" and
# promoted at reduced mass rather than full weight. GUESS — tune after first
# live run if the moons over- or under-demote.
G1_RELEVANCE_PERIPHERAL_FLOOR = 0.5
# Max tokens per moon LLM call. Kept small (256) because each moon makes ONE short
# JSON verdict, not a full response. Three moons × 256 tokens is cheap against the
# ~512-token budget used elsewhere in the chamber.
G1_MOON_MAX_TOKENS = 256

# ─── PHASE 7 GIANTS: G2 SELF-MODEL MOONS (Segment 3 — deterministic, no LLM) ──
# G2_MAGNITUDE_CAP : maximum per-session delta to the self-vector. A single wild
#   session cannot lurch the self-model more than this (normalized units). Gradual
#   accumulation across many sessions is allowed; sudden jumps are clamped and
#   flagged with status="clamped" for audit. GUESS — uncalibrated.
G2_MAGNITUDE_CAP = 0.15
# Escape threshold for the Consistency Gate: if a proposed vector delta's magnitude
# exceeds this, it is held for review as a potential gravitational-containment
# violation (the system "escaping" its own center of gravity). Set to 2× the
# magnitude cap so normal clamped changes pass through but genuinely wild deltas
# get caught. GUESS — tune after live runs.
G2_ESCAPE_THRESHOLD = G2_MAGNITUDE_CAP * 2  # 0.30

# ─── PHASE 7 GIANTS: G2 SANDBOX (Segment 4 — LLM-based, toggle OFF by default) ──
# G2_SANDBOX_ENABLED : master switch for g2_sandbox.try_candidate(). When False,
#   try_candidate() returns {"status": "skipped", ...} with ZERO LLM calls and does
#   NOT import collapse/resonance (offline-safe — same pattern as RING_IDLE_BEHAVIOR).
#   OFF in dev so sleep passes stay cheap; ON in production config.
G2_SANDBOX_ENABLED = False
# How many representative trial prompts to run per candidate. Each prompt runs the
# full pipeline with AND without the proposed change → 2 × N LLM-embedding calls.
# Kept small (3) for first live use; expandable once we trust the metrics.
G2_SANDBOX_TRIAL_PROMPTS = 3
# If applying the candidate shifts total tension by more than this, trial FAILS.
# (Matches g2_selfmodel.json "degradation_threshold.tension_shift_max".)
G2_SANDBOX_TENSION_SHIFT_MAX = 0.30
# If consensus coherence drops below this minimum, trial FAILS. Coherence is
# measured as cosine similarity between the baseline and candidate consensus vectors.
# (Matches g2_selfmodel.json "degradation_threshold.consensus_coherence_min".)
G2_SANDBOX_CONSENSUS_COHERENCE_MIN = 0.70

# ─── PHASE 7 GIANTS: G2 GROWTH POLICY / TIER SYSTEM (Segment 5 — deterministic, no LLM) ──
# TIER1 vs TIER2 boundary for a semantic-anchor / self-vector migration. A proposed
#   G2 change that migrates an anchor direction by MORE than this many normalized units
#   is STRUCTURAL → Tier 2 (held with status="pending_user_approval" until a reviewer
#   approves/rejects). At-or-below stays Tier 1 (autonomous after the moons pass).
# Matches g2_selfmodel.json "_growth_policy.tier_2_notify" (">0.3 units"). GUESS.
G2_TIER2_ANCHOR_MIGRATION = 0.30

# ─── GATE CONFIG PATHS ────────────────────────────────────────────────────────

GATES_CONFIG_PATH = "gates_config.json"

# ─── LM STUDIO CONNECTION ────────────────────────────────────────────────────

LM_STUDIO_HOST = "127.0.0.1"
LM_STUDIO_PORT = 1234
EMBEDDING_MODEL_ID = "text-embedding-allmini"  # confirmed via /v1/models (was a stale filename)
# Main model: auto-detected via /v1/models (first non-embedding available)

# M2 fix (independent-review triage): bounded retry + backoff for embedding calls.
# A single transient LM Studio hiccup (model reloading between calls, brief 5xx,
# connection refused) must not kill the whole pipeline. We retry a few times with
# exponential backoff, then raise a domain-specific EmbeddingUnavailableError instead
# of leaking a raw urllib error to the catch-all.
EMBED_RETRIES = 3                 # total attempts (1 initial + 2 retries). GUESS — tune if slow.
EMBED_RETRY_BACKOFF_S = 1.0       # base backoff; attempt n waits base * (2 ** (n-1)) seconds
# Canonical embedding dimensionality for this model family (all-MiniLM-L6-v2 = 384).
# Single source of truth used by collapse's session-history dir-length guard so a
# malformed persisted wave can't silently poison the superposition. Hardcoded to match
# the model (the AXIS_* vectors are also 384-dim; do not derive from them — they're
# defined later in this file and we want a stable constant here).
EMBEDDING_DIM = 384

# ─── SEMANTIC ANCHORS (Phase 0D — fixed cognitive-space direction per planet) ──
# Distinct, approved values from docs/phase0d_drafts.md §A. These are ALSO written
# into each planets/*.json as "semantic_anchor" (clobber-guarded); this dict is the
# single source of truth used by resonance.py if you prefer not to read JSON per call.
SEMANTIC_ANCHORS = {
    "sage":       [1.000000, 0.400000, -0.500000],
    "magician":   [-0.600000, -0.500000, 0.700000],
    "caregiver":  [0.200000, 1.000000, -0.300000],
    "hero":       [0.400000, -0.200000, 1.000000],
    "everyman":   [0.200000, 0.500000, -0.600000],
    "rebel":      [-0.400000, -1.000000, 0.200000],
    "ruler":      [1.000000, 0.600000, 0.300000],
}
